Paths and reusable definitions were refactored. Stored outputs below are historical, not a fresh execution. See `docs/WORKFLOW.md` at the repository root before rerunning; several stages overwrite results or append Optuna trials.

In [ ]:
# Locate this checkout from the repository root or any notebook subdirectory.
from pathlib import Path
import sys

_root = next((p for p in (Path.cwd(), *Path.cwd().parents)
              if (p / "src" / "steam_recommender" / "paths.py").is_file()), None)
if _root is None:
    raise RuntimeError("Start Jupyter inside the repository checkout.")
sys.path.insert(0, str(_root / "src"))
from steam_recommender import paths as _paths
if Path(_paths.__file__).resolve() != (_root / "src/steam_recommender/paths.py").resolve():
    raise RuntimeError("A different checkout is cached; restart the kernel.")
from steam_recommender.paths import project_root, project_path

In [1]:
# =========================
# BPR EXPERIMENT
# Bayesian Personalized Ranking as binary implicit-feedback baseline
# =========================

import os

os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["OMP_NUM_THREADS"] = "1"

import sys
import numpy as np
import pandas as pd

from scipy.sparse import csr_matrix
from tqdm.auto import tqdm
from threadpoolctl import threadpool_limits

threadpool_limits(1, "blas")


# =========================
# PATHS
# =========================


data_dir = os.path.join(str(project_path("data/processed")))
optuna_results_dir = os.path.join(str(project_path("results/optuna")))
final_results_dir = os.path.join(str(project_path("results/final")))

os.makedirs(optuna_results_dir, exist_ok=True)
os.makedirs(final_results_dir, exist_ok=True)

# =========================
# IMPORTS FROM EXISTING PIPELINE
# =========================

from steam_recommender.splitting import random_user_split_train_val
from steam_recommender.metrics import precision_at_k, recall_at_k, ndcg_at_k, coverage_at_k, delta_gap, diversity_at_k

from implicit.bpr import BayesianPersonalizedRanking


# =========================
# OUTPUT PATHS
# =========================

# =========================
# BPR OUTPUT PATHS
# =========================

bpr_results_dir = os.path.join(str(project_path("results/bpr")))
bpr_optuna_dir = os.path.join(bpr_results_dir, "optuna")
bpr_final_dir = os.path.join(bpr_results_dir, "final")

os.makedirs(bpr_results_dir, exist_ok=True)
os.makedirs(bpr_optuna_dir, exist_ok=True)
os.makedirs(bpr_final_dir, exist_ok=True)

bpr_storage_path = os.path.join(
    bpr_optuna_dir,
    "bpr_studies.db"
)

bpr_optuna_csv_path = os.path.join(
    bpr_optuna_dir,
    "optuna_bpr_results.csv"
)

bpr_test_metrics_path = os.path.join(
    bpr_final_dir,
    "bpr_test_metrics_by_seed.csv"
)

bpr_per_user_ndcg_path = os.path.join(
    bpr_final_dir,
    "bpr_per_user_ndcg.csv"
)

In [2]:
# =========================
# LOAD DATA
# =========================

train_val_df = pd.read_csv(
    os.path.join(data_dir, "users_items_filtered_train_val.csv")
)

test_df = pd.read_csv(
    os.path.join(data_dir, "users_items_filtered_test.csv")
)

for df in [train_val_df, test_df]:
    df["user_id"] = df["user_id"].astype(str)
    df["item_id"] = df["item_id"].astype(str)

print("train_val_df:", train_val_df.shape)
print("test_df:", test_df.shape)

C:\Users\misie\AppData\Local\Temp\ipykernel_7124\866791025.py:5: DtypeWarning: Columns (0: user_id) have mixed types. Specify dtype option on import or set low_memory=False.
  train_val_df = pd.read_csv(

train_val_df: (4591379, 4)
test_df: (541231, 4)

In [3]:
# =========================
# BPR PIPELINE
# =========================

from steam_recommender.bpr import BPRPipeline

In [4]:
# =========================
# TRAIN / VAL SPLIT
# same as ALS Optuna
# =========================

train_df, val_df = random_user_split_train_val(
    train_val_df,
    val_frac=0.1,
    seed=42,
)

print("train_df:", train_df.shape)
print("val_df:", val_df.shape)

train_df: (4104618, 4)
val_df: (486761, 4)

In [5]:
# =========================
# OPTUNA — BPR
# tuned search space after initial exploratory run
# =========================

import optuna

from optuna.samplers import TPESampler
from optuna.pruners import HyperbandPruner
from optuna.storages import RDBStorage


# =========================
# STORAGE
# =========================

storage_path = bpr_storage_path

storage = RDBStorage(
    url=f"sqlite:///{storage_path}",
    engine_kwargs={
        "connect_args": {
            "timeout": 60,
        }
    },
)


# =========================
# OBJECTIVE
# =========================

def objective_bpr(trial):
    """
    Jeden trial = jedna konfiguracja BPR.

    BPR traktujemy jako binarny model implicit-feedback:
    - obserwowana interakcja user-item = pozytyw
    - brak interakcji = kandydat negatywny w samplingu BPR

    Optymalizujemy NDCG@10 na tym samym validation split co ALS.
    """

    # Pierwszy test pokazał najlepsze wyniki raczej dla małych/średnich faktorów.
    factors = trial.suggest_int(
        "factors",
        16,
        96,
        step=8,
    )

    # Pierwszy test wskazywał okolice 0.003–0.009.
    # Dajemy trochę szerszy, ale skoncentrowany zakres.
    learning_rate = trial.suggest_float(
        "learning_rate",
        1e-3,
        2e-2,
        log=True,
    )

    # Pierwszy test wskazywał okolice 0.001–0.003.
    # Dajemy szerszy zakres wokół tego regionu.
    regularization = trial.suggest_float(
        "regularization",
        3e-4,
        2e-2,
        log=True,
    )

    # Dajemy większy zakres, żeby sprawdzić czy BPR był niedotrenowany.
    iterations = trial.suggest_categorical(
        "iterations",
        [50, 100, 150, 200, 300],
    )

    pipeline = BPRPipeline(
        factors=factors,
        iterations=iterations,
        learning_rate=learning_rate,
        regularization=regularization,
        random_state=0,
        num_threads=8,
        verify_negative_samples=True,
    )

    pipeline.fit(train_df, val_df)

    ndcg = pipeline.evaluate_fast(K=10)

    if np.isnan(ndcg):
        return 0.0

    return ndcg


# =========================
# CREATE NEW STUDY
# =========================

study_bpr = optuna.create_study(
    study_name="bpr_binary_tuned",
    direction="maximize",
    sampler=TPESampler(seed=42),
    pruner=HyperbandPruner(),
    storage=storage,
    load_if_exists=False,
)


# =========================
# OPTIONAL: ENQUEUE PREVIOUSLY GOOD REGIONS
# =========================
# Te konfiguracje są blisko dobrych wyników z pierwszego szybkiego testu.
# Optuna sprawdzi je na początku.

study_bpr.enqueue_trial({
    "factors": 24,
    "learning_rate": 0.004,
    "regularization": 0.0028,
    "iterations": 100,
})

study_bpr.enqueue_trial({
    "factors": 40,
    "learning_rate": 0.0055,
    "regularization": 0.0021,
    "iterations": 100,
})

study_bpr.enqueue_trial({
    "factors": 32,
    "learning_rate": 0.007,
    "regularization": 0.0017,
    "iterations": 150,
})

study_bpr.enqueue_trial({
    "factors": 24,
    "learning_rate": 0.004,
    "regularization": 0.0028,
    "iterations": 200,
})


# =========================
# RUN OPTUNA
# =========================

study_bpr.optimize(
    objective_bpr,
    n_trials=150,
    n_jobs=1,
    show_progress_bar=True,
)


# =========================
# RESULTS
# =========================

print("Best BPR NDCG:", study_bpr.best_value)
print("Best BPR params:")
print(study_bpr.best_params)

bpr_trials_df = study_bpr.trials_dataframe()

bpr_results_df = (
    bpr_trials_df
    .sort_values("value", ascending=False)
    .reset_index(drop=True)
)

display(
    bpr_results_df[
        [
            "number",
            "value",
            "params_factors",
            "params_learning_rate",
            "params_regularization",
            "params_iterations",
            "state",
        ]
    ].head(30)
)

bpr_results_df.to_csv(bpr_optuna_csv_path, index=False)

print(f"Saved BPR Optuna results to: {bpr_optuna_csv_path}")
print(f"BPR Optuna storage: {storage_path}")

[I 2026-05-19 19:12:16,235] A new study created in RDB with name: bpr_binary_tuned

  0%|          | 0/150 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-05-19 19:12:30,922] Trial 0 finished with value: 0.19033405367290115 and parameters: {'factors': 24, 'learning_rate': 0.004, 'regularization': 0.0028, 'iterations': 100}. Best is trial 0 with value: 0.19033405367290115.

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-05-19 19:12:46,523] Trial 1 finished with value: 0.17858158276833638 and parameters: {'factors': 40, 'learning_rate': 0.0055, 'regularization': 0.0021, 'iterations': 100}. Best is trial 0 with value: 0.19033405367290115.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:13:06,406] Trial 2 finished with value: 0.14987543242476686 and parameters: {'factors': 32, 'learning_rate': 0.007, 'regularization': 0.0017, 'iterations': 150}. Best is trial 0 with value: 0.19033405367290115.

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-05-19 19:13:29,657] Trial 3 finished with value: 0.16567884602985894 and parameters: {'factors': 24, 'learning_rate': 0.004, 'regularization': 0.0028, 'iterations': 200}. Best is trial 0 with value: 0.19033405367290115.

  0%|          | 0/300 [00:00<?, ?it/s]

[I 2026-05-19 19:14:09,553] Trial 4 finished with value: 0.13546471646557376 and parameters: {'factors': 48, 'learning_rate': 0.017254716573280357, 'regularization': 0.006489502491521281, 'iterations': 300}. Best is trial 0 with value: 0.19033405367290115.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-05-19 19:14:20,737] Trial 5 finished with value: 0.17586402076549795 and parameters: {'factors': 64, 'learning_rate': 0.00834110643236209, 'regularization': 0.0003270886646543574, 'iterations': 50}. Best is trial 0 with value: 0.19033405367290115.

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-05-19 19:14:36,482] Trial 6 finished with value: 0.18094647333541614 and parameters: {'factors': 40, 'learning_rate': 0.004816414530907085, 'regularization': 0.001840558179112292, 'iterations': 100}. Best is trial 0 with value: 0.19033405367290115.

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-05-19 19:15:06,040] Trial 7 finished with value: 0.12666715392325764 and parameters: {'factors': 56, 'learning_rate': 0.01050842133869177, 'regularization': 0.000693917773505113, 'iterations': 200}. Best is trial 0 with value: 0.19033405367290115.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-05-19 19:15:14,873] Trial 8 finished with value: 0.15807113937109293 and parameters: {'factors': 16, 'learning_rate': 0.017160445029754806, 'regularization': 0.017311948854831224, 'iterations': 50}. Best is trial 0 with value: 0.19033405367290115.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-05-19 19:15:24,226] Trial 9 finished with value: 0.18356740366556876 and parameters: {'factors': 24, 'learning_rate': 0.004407984038169242, 'regularization': 0.00034661134929886276, 'iterations': 50}. Best is trial 0 with value: 0.19033405367290115.

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-05-19 19:15:45,473] Trial 10 finished with value: 0.193980541943192 and parameters: {'factors': 96, 'learning_rate': 0.0016393186566385468, 'regularization': 0.00558182994208459, 'iterations': 100}. Best is trial 10 with value: 0.193980541943192.

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-05-19 19:16:07,236] Trial 11 finished with value: 0.1914474757905367 and parameters: {'factors': 96, 'learning_rate': 0.0015569113729753004, 'regularization': 0.006271881650419416, 'iterations': 100}. Best is trial 10 with value: 0.193980541943192.

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-05-19 19:16:29,047] Trial 12 finished with value: 0.18779990726849355 and parameters: {'factors': 96, 'learning_rate': 0.0014566264194659558, 'regularization': 0.008031523010661804, 'iterations': 100}. Best is trial 10 with value: 0.193980541943192.

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-05-19 19:16:50,673] Trial 13 finished with value: 0.18496821430935115 and parameters: {'factors': 96, 'learning_rate': 0.0011432026519834124, 'regularization': 0.00633402796012658, 'iterations': 100}. Best is trial 10 with value: 0.193980541943192.

  0%|          | 0/300 [00:00<?, ?it/s]

[I 2026-05-19 19:17:40,564] Trial 14 finished with value: 0.19366670544067083 and parameters: {'factors': 80, 'learning_rate': 0.002103481408294884, 'regularization': 0.01390209791831492, 'iterations': 300}. Best is trial 10 with value: 0.193980541943192.

  0%|          | 0/300 [00:00<?, ?it/s]

[I 2026-05-19 19:18:31,832] Trial 15 finished with value: 0.18638956492844147 and parameters: {'factors': 80, 'learning_rate': 0.0024998502125998393, 'regularization': 0.01968963088573879, 'iterations': 300}. Best is trial 10 with value: 0.193980541943192.

  0%|          | 0/300 [00:00<?, ?it/s]

[I 2026-05-19 19:19:22,018] Trial 16 finished with value: 0.1965635458265149 and parameters: {'factors': 80, 'learning_rate': 0.002542930713080495, 'regularization': 0.01206917751657076, 'iterations': 300}. Best is trial 16 with value: 0.1965635458265149.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:19:50,284] Trial 17 finished with value: 0.19575068680761099 and parameters: {'factors': 80, 'learning_rate': 0.00258686490486631, 'regularization': 0.010781572308019696, 'iterations': 150}. Best is trial 16 with value: 0.1965635458265149.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:20:16,153] Trial 18 finished with value: 0.19533807987464671 and parameters: {'factors': 72, 'learning_rate': 0.002761007401792165, 'regularization': 0.011154424388448807, 'iterations': 150}. Best is trial 16 with value: 0.1965635458265149.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:20:42,933] Trial 19 finished with value: 0.19996882456702922 and parameters: {'factors': 80, 'learning_rate': 0.0034222311065440335, 'regularization': 0.003998900239676342, 'iterations': 150}. Best is trial 19 with value: 0.19996882456702922.

  0%|          | 0/300 [00:00<?, ?it/s]

[I 2026-05-19 19:21:27,110] Trial 20 finished with value: 0.17557653115678548 and parameters: {'factors': 64, 'learning_rate': 0.003254397404750461, 'regularization': 0.004093735071014374, 'iterations': 300}. Best is trial 19 with value: 0.19996882456702922.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:21:54,210] Trial 21 finished with value: 0.19558562811548263 and parameters: {'factors': 80, 'learning_rate': 0.002390645410152933, 'regularization': 0.010423710784739372, 'iterations': 150}. Best is trial 19 with value: 0.19996882456702922.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:22:22,758] Trial 22 finished with value: 0.20372129152986054 and parameters: {'factors': 88, 'learning_rate': 0.0032067579436970525, 'regularization': 0.004152553830655794, 'iterations': 150}. Best is trial 22 with value: 0.20372129152986054.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:22:51,449] Trial 23 finished with value: 0.17940747439240862 and parameters: {'factors': 88, 'learning_rate': 0.0032650796869543664, 'regularization': 0.0011495811599356504, 'iterations': 150}. Best is trial 22 with value: 0.20372129152986054.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:23:17,223] Trial 24 finished with value: 0.21030539350162433 and parameters: {'factors': 72, 'learning_rate': 0.0019146805779491668, 'regularization': 0.004024779614919073, 'iterations': 150}. Best is trial 24 with value: 0.21030539350162433.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:23:42,028] Trial 25 finished with value: 0.21104971566023364 and parameters: {'factors': 64, 'learning_rate': 0.001837962624903009, 'regularization': 0.004057105193346063, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:24:07,225] Trial 26 finished with value: 0.20114994084866933 and parameters: {'factors': 64, 'learning_rate': 0.00104591056608708, 'regularization': 0.00395668261277857, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:24:30,983] Trial 27 finished with value: 0.19717515826705168 and parameters: {'factors': 56, 'learning_rate': 0.0018767286621681981, 'regularization': 0.001366038860639291, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:24:57,932] Trial 28 finished with value: 0.20896297489853216 and parameters: {'factors': 72, 'learning_rate': 0.0013323325144695445, 'regularization': 0.0032247284703589008, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:25:24,152] Trial 29 finished with value: 0.20974563016789596 and parameters: {'factors': 72, 'learning_rate': 0.0013419073264910393, 'regularization': 0.002834402968434899, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-05-19 19:25:55,425] Trial 30 finished with value: 0.1948999308469893 and parameters: {'factors': 56, 'learning_rate': 0.0012421865333903648, 'regularization': 0.0009326295338117261, 'iterations': 200}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:26:23,105] Trial 31 finished with value: 0.20902111466618895 and parameters: {'factors': 72, 'learning_rate': 0.001327887714847725, 'regularization': 0.002902025080531038, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:26:50,462] Trial 32 finished with value: 0.20453362735256306 and parameters: {'factors': 72, 'learning_rate': 0.0019206717352730587, 'regularization': 0.002137062274975046, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:27:16,654] Trial 33 finished with value: 0.20597914570404746 and parameters: {'factors': 64, 'learning_rate': 0.001006944363396325, 'regularization': 0.0026346632918724687, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:27:42,651] Trial 34 finished with value: 0.21042998775869753 and parameters: {'factors': 72, 'learning_rate': 0.0017522553196313675, 'regularization': 0.0033210157562347975, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:28:04,925] Trial 35 finished with value: 0.20886266224524663 and parameters: {'factors': 48, 'learning_rate': 0.0017373751778121305, 'regularization': 0.004727352716306269, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:28:29,474] Trial 36 finished with value: 0.20168806514600293 and parameters: {'factors': 64, 'learning_rate': 0.0020906564642920074, 'regularization': 0.008136327834354369, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-05-19 19:28:57,892] Trial 37 finished with value: 0.15408177792422775 and parameters: {'factors': 48, 'learning_rate': 0.005745133843864319, 'regularization': 0.0021983165690102205, 'iterations': 200}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:29:26,686] Trial 38 finished with value: 0.20588089706330467 and parameters: {'factors': 88, 'learning_rate': 0.0015124288833475027, 'regularization': 0.001674592808569008, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-05-19 19:29:38,582] Trial 39 finished with value: 0.1898928642518724 and parameters: {'factors': 72, 'learning_rate': 0.0020935220398249545, 'regularization': 0.003403605972265728, 'iterations': 50}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:30:02,065] Trial 40 finished with value: 0.15299367696256758 and parameters: {'factors': 56, 'learning_rate': 0.013410737297462637, 'regularization': 0.004983831805942581, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:30:28,563] Trial 41 finished with value: 0.2094274224254045 and parameters: {'factors': 72, 'learning_rate': 0.0013701936350776697, 'regularization': 0.003017481574078637, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:30:53,736] Trial 42 finished with value: 0.20930032620227876 and parameters: {'factors': 64, 'learning_rate': 0.0011603847559374942, 'regularization': 0.002464095647268143, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:31:19,704] Trial 43 finished with value: 0.20331035844328713 and parameters: {'factors': 72, 'learning_rate': 0.001666665142722112, 'regularization': 0.0016625579707702867, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:31:43,537] Trial 44 finished with value: 0.20994854169807248 and parameters: {'factors': 56, 'learning_rate': 0.0013739302184150636, 'regularization': 0.0032788618929249715, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-05-19 19:31:53,768] Trial 45 finished with value: 0.17283990615712147 and parameters: {'factors': 40, 'learning_rate': 0.001781170315247984, 'regularization': 0.0073627644757377625, 'iterations': 50}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-05-19 19:32:23,035] Trial 46 finished with value: 0.20002260923395146 and parameters: {'factors': 48, 'learning_rate': 0.00222440695428299, 'regularization': 0.0035111292659640962, 'iterations': 200}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:36:18,650] Trial 47 finished with value: 0.2052787623907745 and parameters: {'factors': 32, 'learning_rate': 0.001516930136278305, 'regularization': 0.005206145702898483, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:36:50,543] Trial 48 finished with value: 0.20921066502418592 and parameters: {'factors': 64, 'learning_rate': 0.0011764508701265148, 'regularization': 0.0019245608090877344, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-05-19 19:37:02,866] Trial 49 finished with value: 0.20432267299437504 and parameters: {'factors': 56, 'learning_rate': 0.002786387557556681, 'regularization': 0.0024772304984983047, 'iterations': 50}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-05-19 19:37:18,023] Trial 50 finished with value: 0.18430942179735424 and parameters: {'factors': 16, 'learning_rate': 0.003934846679421445, 'regularization': 0.005972636461271242, 'iterations': 100}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:37:49,006] Trial 51 finished with value: 0.20924177521491133 and parameters: {'factors': 72, 'learning_rate': 0.001376927474156948, 'regularization': 0.0031008986261875605, 'iterations': 150}. Best is trial 25 with value: 0.21104971566023364.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:38:19,216] Trial 52 finished with value: 0.2110890030865056 and parameters: {'factors': 56, 'learning_rate': 0.00160109817857125, 'regularization': 0.0028698274439098695, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:38:49,857] Trial 53 finished with value: 0.20996486739249517 and parameters: {'factors': 56, 'learning_rate': 0.001914601246874519, 'regularization': 0.00447947445557087, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:39:12,818] Trial 54 finished with value: 0.2023551593629713 and parameters: {'factors': 40, 'learning_rate': 0.0019545033386875127, 'regularization': 0.007147321849539557, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/300 [00:00<?, ?it/s]

[I 2026-05-19 19:39:56,229] Trial 55 finished with value: 0.20274901891956962 and parameters: {'factors': 56, 'learning_rate': 0.0016545968126614804, 'regularization': 0.0043313680784616265, 'iterations': 300}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:40:19,081] Trial 56 finished with value: 0.18115185350918692 and parameters: {'factors': 48, 'learning_rate': 0.0022044147882604725, 'regularization': 0.0004048570820615607, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:40:43,336] Trial 57 finished with value: 0.20775488906827272 and parameters: {'factors': 56, 'learning_rate': 0.0023257583978938505, 'regularization': 0.0035161340384324015, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:41:08,644] Trial 58 finished with value: 0.19321497964434112 and parameters: {'factors': 64, 'learning_rate': 0.0015496218546530108, 'regularization': 0.009352288247661024, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-05-19 19:41:26,946] Trial 59 finished with value: 0.18094317950989164 and parameters: {'factors': 64, 'learning_rate': 0.008867873059904864, 'regularization': 0.00481431039025865, 'iterations': 100}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:41:50,031] Trial 60 finished with value: 0.20600191454415853 and parameters: {'factors': 48, 'learning_rate': 0.0028357788311632343, 'regularization': 0.0057370106637456425, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:42:15,669] Trial 61 finished with value: 0.20687709675335508 and parameters: {'factors': 64, 'learning_rate': 0.0012503753870828412, 'regularization': 0.0037235855148619033, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:42:39,722] Trial 62 finished with value: 0.20916751395205782 and parameters: {'factors': 56, 'learning_rate': 0.0018059148275325547, 'regularization': 0.002607100575079357, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:43:07,611] Trial 63 finished with value: 0.19941156319804604 and parameters: {'factors': 80, 'learning_rate': 0.0010856984034614803, 'regularization': 0.004273610792987799, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:43:34,021] Trial 64 finished with value: 0.20925820914212057 and parameters: {'factors': 72, 'learning_rate': 0.0014578939196414782, 'regularization': 0.0022409748724469313, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-05-19 19:44:06,020] Trial 65 finished with value: 0.20113167426527656 and parameters: {'factors': 64, 'learning_rate': 0.0019578962394627307, 'regularization': 0.00293207060025487, 'iterations': 200}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:44:29,868] Trial 66 finished with value: 0.20624647000300655 and parameters: {'factors': 56, 'learning_rate': 0.0016631859337979161, 'regularization': 0.0019129639306312562, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/300 [00:00<?, ?it/s]

[I 2026-05-19 19:45:22,064] Trial 67 finished with value: 0.1915177846185338 and parameters: {'factors': 80, 'learning_rate': 0.001228192492684515, 'regularization': 0.0013939716496846567, 'iterations': 300}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:45:44,793] Trial 68 finished with value: 0.20525490919281925 and parameters: {'factors': 48, 'learning_rate': 0.002537181529188185, 'regularization': 0.0037313944558749934, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:46:11,738] Trial 69 finished with value: 0.2032846901930123 and parameters: {'factors': 72, 'learning_rate': 0.0013681347695356165, 'regularization': 0.004709842387342308, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-05-19 19:46:29,271] Trial 70 finished with value: 0.19930863769227689 and parameters: {'factors': 56, 'learning_rate': 0.001975127114563874, 'regularization': 0.005409096121582208, 'iterations': 100}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:46:55,610] Trial 71 finished with value: 0.21028006139435362 and parameters: {'factors': 72, 'learning_rate': 0.001419896478928182, 'regularization': 0.0028003298678727613, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:47:21,912] Trial 72 finished with value: 0.21015233948956039 and parameters: {'factors': 72, 'learning_rate': 0.001579527805875171, 'regularization': 0.002692063527640276, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:47:47,360] Trial 73 finished with value: 0.20882868063322205 and parameters: {'factors': 64, 'learning_rate': 0.0015978184890798627, 'regularization': 0.0023175963890093645, 'iterations': 150}. Best is trial 52 with value: 0.2110890030865056.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:48:16,036] Trial 74 finished with value: 0.2112020500129314 and parameters: {'factors': 88, 'learning_rate': 0.0017820411784462565, 'regularization': 0.0032039847818838216, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:48:45,917] Trial 75 finished with value: 0.20978234791833275 and parameters: {'factors': 96, 'learning_rate': 0.0018376978523327388, 'regularization': 0.0027827575724012586, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:49:14,377] Trial 76 finished with value: 0.21042042063093214 and parameters: {'factors': 88, 'learning_rate': 0.0020863467135563657, 'regularization': 0.004391762741208964, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-05-19 19:49:27,206] Trial 77 finished with value: 0.20821499248668693 and parameters: {'factors': 88, 'learning_rate': 0.005284985157165557, 'regularization': 0.0038753301127173456, 'iterations': 50}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:49:56,148] Trial 78 finished with value: 0.18494571966953713 and parameters: {'factors': 88, 'learning_rate': 0.00304107521563202, 'regularization': 0.0014605211483598877, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:50:23,513] Trial 79 finished with value: 0.21081119244309385 and parameters: {'factors': 80, 'learning_rate': 0.0017283345975345576, 'regularization': 0.003217695791507202, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-05-19 19:51:00,157] Trial 80 finished with value: 0.20673007543525698 and parameters: {'factors': 88, 'learning_rate': 0.002155411660376337, 'regularization': 0.006790901073582377, 'iterations': 200}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:51:27,981] Trial 81 finished with value: 0.2102877449291514 and parameters: {'factors': 80, 'learning_rate': 0.0015027508348295223, 'regularization': 0.003225314058065672, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:51:56,292] Trial 82 finished with value: 0.20706797970792534 and parameters: {'factors': 80, 'learning_rate': 0.0023486874529898474, 'regularization': 0.003304994684767127, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:52:24,333] Trial 83 finished with value: 0.21070573401247888 and parameters: {'factors': 80, 'learning_rate': 0.001692839626759686, 'regularization': 0.0031056696341264602, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:52:51,768] Trial 84 finished with value: 0.2099625656115914 and parameters: {'factors': 80, 'learning_rate': 0.001732515372992301, 'regularization': 0.0040799047729490065, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:53:21,451] Trial 85 finished with value: 0.21019639061474016 and parameters: {'factors': 88, 'learning_rate': 0.0019892737335975553, 'regularization': 0.0031769389064588644, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/300 [00:00<?, ?it/s]

[I 2026-05-19 19:54:14,371] Trial 86 finished with value: 0.18649039444433982 and parameters: {'factors': 80, 'learning_rate': 0.0017705317470342338, 'regularization': 0.002066597614319898, 'iterations': 300}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:54:44,609] Trial 87 finished with value: 0.21068372670536062 and parameters: {'factors': 88, 'learning_rate': 0.002083005976363409, 'regularization': 0.00374295559678755, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:55:15,977] Trial 88 finished with value: 0.20982457522616002 and parameters: {'factors': 96, 'learning_rate': 0.0020793676300058807, 'regularization': 0.005212641545972315, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:55:46,260] Trial 89 finished with value: 0.20860720469405716 and parameters: {'factors': 88, 'learning_rate': 0.0024101145209144297, 'regularization': 0.0037217685396935666, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:56:16,314] Trial 90 finished with value: 0.20422180397420664 and parameters: {'factors': 88, 'learning_rate': 0.003742803753298324, 'regularization': 0.006075730106665075, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:56:45,156] Trial 91 finished with value: 0.20969701789011763 and parameters: {'factors': 80, 'learning_rate': 0.0014954620156058729, 'regularization': 0.0024668050674541923, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:57:13,942] Trial 92 finished with value: 0.2049426443295468 and parameters: {'factors': 80, 'learning_rate': 0.0026385055354229995, 'regularization': 0.0034034925437376753, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:57:43,557] Trial 93 finished with value: 0.14691721345979664 and parameters: {'factors': 88, 'learning_rate': 0.019573178426317676, 'regularization': 0.004445694225448705, 'iterations': 150}. Best is trial 74 with value: 0.2112020500129314.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:58:14,304] Trial 94 finished with value: 0.21153390905339264 and parameters: {'factors': 96, 'learning_rate': 0.0017200816114582526, 'regularization': 0.0035648980497263883, 'iterations': 150}. Best is trial 94 with value: 0.21153390905339264.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-05-19 19:58:27,900] Trial 95 finished with value: 0.17976712321439584 and parameters: {'factors': 96, 'learning_rate': 0.0017102092494461433, 'regularization': 0.003636175524111701, 'iterations': 50}. Best is trial 94 with value: 0.21153390905339264.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:58:59,474] Trial 96 finished with value: 0.20709979298684014 and parameters: {'factors': 96, 'learning_rate': 0.002259280825510412, 'regularization': 0.003011845963681957, 'iterations': 150}. Best is trial 94 with value: 0.21153390905339264.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 19:59:31,632] Trial 97 finished with value: 0.20761003961289703 and parameters: {'factors': 96, 'learning_rate': 0.0016167099708799483, 'regularization': 0.0047134209250252876, 'iterations': 150}. Best is trial 94 with value: 0.21153390905339264.

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-05-19 19:59:52,593] Trial 98 finished with value: 0.20564537432132599 and parameters: {'factors': 88, 'learning_rate': 0.002068806855124943, 'regularization': 0.004124015640605017, 'iterations': 100}. Best is trial 94 with value: 0.21153390905339264.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:00:22,343] Trial 99 finished with value: 0.21081806783256202 and parameters: {'factors': 88, 'learning_rate': 0.001851852116486548, 'regularization': 0.003968572580768448, 'iterations': 150}. Best is trial 94 with value: 0.21153390905339264.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:00:51,460] Trial 100 finished with value: 0.16628998996515854 and parameters: {'factors': 88, 'learning_rate': 0.006662669431497118, 'regularization': 0.002369147677729761, 'iterations': 150}. Best is trial 94 with value: 0.21153390905339264.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:01:21,835] Trial 101 finished with value: 0.2112701723378574 and parameters: {'factors': 96, 'learning_rate': 0.0018475746696908109, 'regularization': 0.0040105557581981525, 'iterations': 150}. Best is trial 94 with value: 0.21153390905339264.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:01:52,761] Trial 102 finished with value: 0.2116458850425016 and parameters: {'factors': 96, 'learning_rate': 0.001844618038805879, 'regularization': 0.0038641943288655655, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:02:23,527] Trial 103 finished with value: 0.21153426921485358 and parameters: {'factors': 96, 'learning_rate': 0.0018738113607815812, 'regularization': 0.0035276967020751544, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:02:54,350] Trial 104 finished with value: 0.209954478819293 and parameters: {'factors': 96, 'learning_rate': 0.0018757072218282141, 'regularization': 0.0029728910366352583, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:03:25,777] Trial 105 finished with value: 0.20678253042799316 and parameters: {'factors': 96, 'learning_rate': 0.001258979684488732, 'regularization': 0.003567290194405131, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:03:57,451] Trial 106 finished with value: 0.21124080247435012 and parameters: {'factors': 96, 'learning_rate': 0.0018293489290224154, 'regularization': 0.003974007651309434, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-05-19 20:04:38,059] Trial 107 finished with value: 0.20952555274422982 and parameters: {'factors': 96, 'learning_rate': 0.0018138251959592755, 'regularization': 0.005055117810820995, 'iterations': 200}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:05:10,632] Trial 108 finished with value: 0.21026697744499454 and parameters: {'factors': 96, 'learning_rate': 0.001664758203778057, 'regularization': 0.002520338020861426, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/300 [00:00<?, ?it/s]

[I 2026-05-19 20:06:12,231] Trial 109 finished with value: 0.20237297936577714 and parameters: {'factors': 96, 'learning_rate': 0.00129472278155603, 'regularization': 0.002706916352881277, 'iterations': 300}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:06:42,596] Trial 110 finished with value: 0.2035831905286658 and parameters: {'factors': 96, 'learning_rate': 0.0015669425650903933, 'regularization': 0.005639212051657894, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:07:13,019] Trial 111 finished with value: 0.21144551414739782 and parameters: {'factors': 96, 'learning_rate': 0.0018742413849345194, 'regularization': 0.0038786667253370485, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:07:43,432] Trial 112 finished with value: 0.21113282978379475 and parameters: {'factors': 96, 'learning_rate': 0.0018296141168095124, 'regularization': 0.0039802750199336955, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:08:14,131] Trial 113 finished with value: 0.21094399375062206 and parameters: {'factors': 96, 'learning_rate': 0.0018762893662957157, 'regularization': 0.004031798741338638, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:08:45,370] Trial 114 finished with value: 0.21121078937515297 and parameters: {'factors': 96, 'learning_rate': 0.0018616024019518559, 'regularization': 0.004009235513759087, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:09:16,662] Trial 115 finished with value: 0.2104937955774976 and parameters: {'factors': 96, 'learning_rate': 0.002239218092839941, 'regularization': 0.004543707012992061, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:09:48,268] Trial 116 finished with value: 0.20424016361816513 and parameters: {'factors': 96, 'learning_rate': 0.0014405111566638464, 'regularization': 0.004974475655709025, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:10:19,430] Trial 117 finished with value: 0.2108499937636622 and parameters: {'factors': 96, 'learning_rate': 0.0019799790382225633, 'regularization': 0.004357087368332855, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:10:51,182] Trial 118 finished with value: 0.209265166098734 and parameters: {'factors': 96, 'learning_rate': 0.0023971310389466548, 'regularization': 0.0038800350434991977, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:11:23,289] Trial 119 finished with value: 0.21136647905038353 and parameters: {'factors': 96, 'learning_rate': 0.0018828955996870332, 'regularization': 0.003472220900416734, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/100 [00:00<?, ?it/s]

[I 2026-05-19 20:11:46,040] Trial 120 finished with value: 0.20667979286858099 and parameters: {'factors': 96, 'learning_rate': 0.0019628357889764016, 'regularization': 0.0035620151725274996, 'iterations': 100}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:12:18,874] Trial 121 finished with value: 0.2107012196535148 and parameters: {'factors': 96, 'learning_rate': 0.0018108939327805373, 'regularization': 0.0041601113821338135, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:12:51,007] Trial 122 finished with value: 0.20938363492709539 and parameters: {'factors': 96, 'learning_rate': 0.002175847123621165, 'regularization': 0.003355103808399395, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:13:22,690] Trial 123 finished with value: 0.211351834262772 and parameters: {'factors': 96, 'learning_rate': 0.001884514028040979, 'regularization': 0.003942283584434214, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:13:54,243] Trial 124 finished with value: 0.20727985350559086 and parameters: {'factors': 96, 'learning_rate': 0.0015854055395469965, 'regularization': 0.0047847573522702145, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/50 [00:00<?, ?it/s]

[I 2026-05-19 20:14:08,330] Trial 125 finished with value: 0.18997861033955318 and parameters: {'factors': 96, 'learning_rate': 0.0020012781598860163, 'regularization': 0.002905220706539869, 'iterations': 50}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:14:29,190] Trial 126 finished with value: 0.20024120050698904 and parameters: {'factors': 32, 'learning_rate': 0.0014630088433490833, 'regularization': 0.0064411050411143705, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:15:01,954] Trial 127 finished with value: 0.21161340550162874 and parameters: {'factors': 96, 'learning_rate': 0.001683992097378975, 'regularization': 0.0034788351854369132, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:15:35,463] Trial 128 finished with value: 0.21111901048996617 and parameters: {'factors': 96, 'learning_rate': 0.0016898457283479017, 'regularization': 0.003499327119088276, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:16:07,712] Trial 129 finished with value: 0.19155557224579936 and parameters: {'factors': 96, 'learning_rate': 0.0044236108255440625, 'regularization': 0.003725708034471684, 'iterations': 150}. Best is trial 102 with value: 0.2116458850425016.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:16:38,199] Trial 130 finished with value: 0.21168990177795607 and parameters: {'factors': 96, 'learning_rate': 0.0017527760702097234, 'regularization': 0.0033894740932076286, 'iterations': 150}. Best is trial 130 with value: 0.21168990177795607.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:17:08,707] Trial 131 finished with value: 0.2115382628037158 and parameters: {'factors': 96, 'learning_rate': 0.0017337553670383294, 'regularization': 0.003345565683516046, 'iterations': 150}. Best is trial 130 with value: 0.21168990177795607.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:17:39,449] Trial 132 finished with value: 0.2118049701017791 and parameters: {'factors': 96, 'learning_rate': 0.0017602669790432763, 'regularization': 0.0032374923658688454, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:18:09,914] Trial 133 finished with value: 0.21133637392047142 and parameters: {'factors': 96, 'learning_rate': 0.0017513729700980303, 'regularization': 0.0031680636480196536, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:18:40,852] Trial 134 finished with value: 0.15221439060146874 and parameters: {'factors': 96, 'learning_rate': 0.013154177474868725, 'regularization': 0.0030326214650057914, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:19:11,380] Trial 135 finished with value: 0.21092513121907705 and parameters: {'factors': 96, 'learning_rate': 0.0015250807699030372, 'regularization': 0.0026779482659110435, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:19:42,594] Trial 136 finished with value: 0.21094877105831908 and parameters: {'factors': 96, 'learning_rate': 0.0019229473533809538, 'regularization': 0.0034678820339184065, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:20:13,818] Trial 137 finished with value: 0.2052017369676305 and parameters: {'factors': 96, 'learning_rate': 0.0016405810390508419, 'regularization': 0.00539254205162117, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/200 [00:00<?, ?it/s]

[I 2026-05-19 20:20:51,885] Trial 138 finished with value: 0.20725635915686802 and parameters: {'factors': 88, 'learning_rate': 0.0021623272941867595, 'regularization': 0.004396710882334835, 'iterations': 200}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/300 [00:00<?, ?it/s]

[I 2026-05-19 20:21:49,530] Trial 139 finished with value: 0.1970123917281802 and parameters: {'factors': 96, 'learning_rate': 0.0017429738314885257, 'regularization': 0.0032600097145640125, 'iterations': 300}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:22:20,950] Trial 140 finished with value: 0.18729279133677468 and parameters: {'factors': 96, 'learning_rate': 0.0020446944523455786, 'regularization': 0.0006227415358121408, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:22:51,562] Trial 141 finished with value: 0.21144074425972217 and parameters: {'factors': 96, 'learning_rate': 0.0017655398316892927, 'regularization': 0.003148436636387925, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:23:22,649] Trial 142 finished with value: 0.21110233569814682 and parameters: {'factors': 96, 'learning_rate': 0.0016195536662314935, 'regularization': 0.0036666717288032814, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:23:54,794] Trial 143 finished with value: 0.21080552282522935 and parameters: {'factors': 96, 'learning_rate': 0.001740332230177506, 'regularization': 0.0028446368659384097, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:24:25,177] Trial 144 finished with value: 0.21027580640955343 and parameters: {'factors': 88, 'learning_rate': 0.0019154098730523432, 'regularization': 0.0031482837642209205, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:24:57,496] Trial 145 finished with value: 0.209726145457847 and parameters: {'factors': 96, 'learning_rate': 0.0015257216345107428, 'regularization': 0.003916114760035565, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:25:28,538] Trial 146 finished with value: 0.21127868035558842 and parameters: {'factors': 96, 'learning_rate': 0.001861948467100342, 'regularization': 0.0033589659302270506, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:25:58,464] Trial 147 finished with value: 0.21074164391805447 and parameters: {'factors': 88, 'learning_rate': 0.0014198807579548266, 'regularization': 0.002591869770514922, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:26:28,703] Trial 148 finished with value: 0.20941418053701952 and parameters: {'factors': 96, 'learning_rate': 0.0022761664304105722, 'regularization': 0.0035072657978117753, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.

  0%|          | 0/150 [00:00<?, ?it/s]

[I 2026-05-19 20:26:58,814] Trial 149 finished with value: 0.20709626101921752 and parameters: {'factors': 96, 'learning_rate': 0.0017144327183312787, 'regularization': 0.002075523967842273, 'iterations': 150}. Best is trial 132 with value: 0.2118049701017791.
Best BPR NDCG: 0.2118049701017791
Best BPR params:
{'factors': 96, 'learning_rate': 0.0017602669790432763, 'regularization': 0.0032374923658688454, 'iterations': 150}

,number,value,params_factors,params_learning_rate,params_regularization,params_iterations,state
0,132,0.211805,96,0.001760,0.003237,150,COMPLETE
1,130,0.211690,96,0.001753,0.003389,150,COMPLETE
2,102,0.211646,96,0.001845,0.003864,150,COMPLETE
3,127,0.211613,96,0.001684,0.003479,150,COMPLETE
4,131,0.211538,96,0.001734,0.003346,150,COMPLETE
5,103,0.211534,96,0.001874,0.003528,150,COMPLETE
6,94,0.211534,96,0.001720,0.003565,150,COMPLETE
7,111,0.211446,96,0.001874,0.003879,150,COMPLETE
8,141,0.211441,96,0.001766,0.003148,150,COMPLETE
9,119,0.211366,96,0.001883,0.003472,150,COMPLETE
10,123,0.211352,96,0.001885,0.003942,150,COMPLETE
11,133,0.211336,96,0.001751,0.003168,150,COMPLETE
12,146,0.211279,96,0.001862,0.003359,150,COMPLETE
13,101,0.211270,96,0.001848,0.004011,150,COMPLETE
14,106,0.211241,96,0.001829,0.003974,150,COMPLETE
15,114,0.211211,96,0.001862,0.004009,150,COMPLETE
16,74,0.211202,88,0.001782,0.003204,150,COMPLETE
17,112,0.211133,96,0.001830,0.003980,150,COMPLETE
18,128,0.211119,96,0.001690,0.003499,150,COMPLETE
19,142,0.211102,96,0.001620,0.003667,150,COMPLETE
20,52,0.211089,56,0.001601,0.002870,150,COMPLETE
21,25,0.211050,64,0.001838,0.004057,150,COMPLETE
22,136,0.210949,96,0.001923,0.003468,150,COMPLETE
23,113,0.210944,96,0.001876,0.004032,150,COMPLETE
24,135,0.210925,96,0.001525,0.002678,150,COMPLETE
25,117,0.210850,96,0.001980,0.004357,150,COMPLETE
26,99,0.210818,88,0.001852,0.003969,150,COMPLETE
27,79,0.210811,80,0.001728,0.003218,150,COMPLETE
28,143,0.210806,96,0.001740,0.002845,150,COMPLETE
29,147,0.210742,88,0.001420,0.002592,150,COMPLETE

Saved BPR Optuna results to: D:\Studiowe\Licencjat\modele\bpr_results\optuna\optuna_bpr_results.csv
BPR Optuna storage: D:\Studiowe\Licencjat\modele\bpr_results\optuna\bpr_studies.db

In [6]:
# =========================
# FINAL TEST — BPR
# =========================

best_bpr_params = study_bpr.best_params

K = 10
seeds = [0, 1, 2, 3, 4]

metric_rows = []
per_user_rows = []

for seed in tqdm(seeds, desc="BPR final test"):
    pipeline = BPRPipeline(
        factors=int(best_bpr_params["factors"]),
        iterations=int(best_bpr_params["iterations"]),
        learning_rate=float(best_bpr_params["learning_rate"]),
        regularization=float(best_bpr_params["regularization"]),
        random_state=seed,
        num_threads=8,
        verify_negative_samples=True,
    )

    results, recommendations, user_ndcg = pipeline.refit_full_and_test(
        train_df=train_val_df,
        test_df=test_df,
        K=K,
        return_per_user=True,
        verbose=False,
    )

    metric_row = {
        "model": "BPR",
        "function": "bpr_binary",
        "function_label": "BPR",
        "seed": seed,
        "factors": int(best_bpr_params["factors"]),
        "iterations": int(best_bpr_params["iterations"]),
        "learning_rate": float(best_bpr_params["learning_rate"]),
        "regularization": float(best_bpr_params["regularization"]),
    }

    metric_row.update(results)
    metric_rows.append(metric_row)

    for user_id, ndcg_value in user_ndcg.items():
        per_user_rows.append({
            "model": "BPR",
            "function": "bpr_binary",
            "function_label": "BPR",
            "seed": seed,
            "user_id": user_id,
            f"ndcg@{K}": ndcg_value,
        })


bpr_test_metrics_df = pd.DataFrame(metric_rows)
bpr_per_user_ndcg_df = pd.DataFrame(per_user_rows)

display(bpr_test_metrics_df)
display(bpr_per_user_ndcg_df.head())

bpr_test_metrics_df.to_csv(bpr_test_metrics_path, index=False)
bpr_per_user_ndcg_df.to_csv(bpr_per_user_ndcg_path, index=False)

print(f"Saved BPR test metrics to: {bpr_test_metrics_path}")
print(f"Saved BPR per-user NDCG to: {bpr_per_user_ndcg_path}")

BPR final test:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/150 [00:00<?, ?it/s]

  0%|          | 0/150 [00:00<?, ?it/s]

  0%|          | 0/150 [00:00<?, ?it/s]

  0%|          | 0/150 [00:00<?, ?it/s]

  0%|          | 0/150 [00:00<?, ?it/s]

,model,function,function_label,seed,factors,iterations,learning_rate,regularization,precision@10,recall@10,ndcg@10,coverage@10,delta_gap@10,diversity@10,users_evaluated
0,BPR,bpr_binary,BPR,0,96,150,0.00176,0.003237,0.132896,0.261243,0.269803,0.305827,-0.079945,0.549656,62944
1,BPR,bpr_binary,BPR,1,96,150,0.00176,0.003237,0.132508,0.260874,0.270121,0.303653,-0.086190,0.550582,62944
2,BPR,bpr_binary,BPR,2,96,150,0.00176,0.003237,0.133287,0.262033,0.271325,0.303979,-0.078522,0.549720,62944
3,BPR,bpr_binary,BPR,3,96,150,0.00176,0.003237,0.132893,0.261749,0.270106,0.303870,-0.071132,0.550916,62944
4,BPR,bpr_binary,BPR,4,96,150,0.00176,0.003237,0.132673,0.261104,0.269937,0.302348,-0.078663,0.548628,62944

  model    function function_label  seed            user_id   ndcg@10
0   BPR  bpr_binary            BPR     0            --000--  0.100867
1   BPR  bpr_binary            BPR     0            --ace--  0.000000
2   BPR  bpr_binary            BPR     0          --ionex--  0.148041
3   BPR  bpr_binary            BPR     0       -2SV-vuLB-Kg  0.079457
4   BPR  bpr_binary            BPR     0  -404PageNotFound-  0.220092

Saved BPR test metrics to: D:\Studiowe\Licencjat\modele\bpr_results\final\bpr_test_metrics_by_seed.csv
Saved BPR per-user NDCG to: D:\Studiowe\Licencjat\modele\bpr_results\final\bpr_per_user_ndcg.csv

In [7]:

# =========================
# BPR SUMMARY
# =========================

metric_cols = [
    f"precision@{K}",
    f"recall@{K}",
    f"ndcg@{K}",
    f"coverage@{K}",
    f"delta_gap@{K}",
    f"diversity@{K}",
    "users_evaluated",
]

summary = {}

for metric in metric_cols:
    summary[f"{metric}_mean"] = bpr_test_metrics_df[metric].mean()
    summary[f"{metric}_std"] = bpr_test_metrics_df[metric].std(ddof=1)

bpr_summary_df = pd.DataFrame([summary])

display(bpr_summary_df)

print("BPR summary:")
for metric in metric_cols:
    mean = summary[f"{metric}_mean"]
    std = summary[f"{metric}_std"]

    if metric == "users_evaluated":
        print(f"{metric}: {mean:.0f} ± {std:.0f}")
    else:
        print(f"{metric}: {mean:.4f} ± {std:.4f}")

,precision@10_mean,precision@10_std,recall@10_mean,recall@10_std,ndcg@10_mean,ndcg@10_std,coverage@10_mean,coverage@10_std,delta_gap@10_mean,delta_gap@10_std,diversity@10_mean,diversity@10_std,users_evaluated_mean,users_evaluated_std
0,0.132851,0.000293,0.261401,0.000477,0.270258,0.00061,0.303936,0.001243,-0.078891,0.005357,0.5499,0.000896,62944.0,0.0

BPR summary:
precision@10: 0.1329 ± 0.0003
recall@10: 0.2614 ± 0.0005
ndcg@10: 0.2703 ± 0.0006
coverage@10: 0.3039 ± 0.0012
delta_gap@10: -0.0789 ± 0.0054
diversity@10: 0.5499 ± 0.0009
users_evaluated: 62944 ± 0

In [3]:
from pathlib import Path
import pandas as pd

OUTPUT_DIR = Path(str(project_path("results/bpr/final")))
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

bpr_summary_pretty = pd.DataFrame([
    {
        "Model": "BPR",
        "precision@10": "0.1329 ± 0.0003",
        "recall@10": "0.2614 ± 0.0005",
        "ndcg@10": "0.2703 ± 0.0006",
        "coverage@10": "0.3039 ± 0.0012",
        "delta_gap@10": "-0.0789 ± 0.0054",
        "diversity@10": "0.5499 ± 0.0009",
        "users_evaluated": "62944 ± 0",
    }
])

output_path = OUTPUT_DIR / "bpr_test_metrics_summary_pretty.csv"

bpr_summary_pretty.to_csv(output_path, index=False, encoding="utf-8")

print(f"Saved to: {output_path}")
display(bpr_summary_pretty)

Saved to: D:\Studiowe\Licencjat\modele\bpr_results\final\bpr_test_metrics_summary_pretty.csv

,Model,precision@10,recall@10,ndcg@10,coverage@10,delta_gap@10,diversity@10,users_evaluated
0,BPR,0.1329 ± 0.0003,0.2614 ± 0.0005,0.2703 ± 0.0006,0.3039 ± 0.0012,-0.0789 ± 0.0054,0.5499 ± 0.0009,62944 ± 0